echo "Welcome to Paragraph. "
echo ""
echo "Configure a working session with:"
echo "?- consult('/opt/paragraph/prolog/paragraph_conf.pl')."
echo "?- paragraph_setup."
echo ""
echo "Load some BDSL definitions with:"
echo "?- consult('/opt/paragraph/prolog/bdsl_lib/nodeproj.bdsl.pl')." 
echo "" 
echo "Start a working session with:"
echo "?- consult('/opt/paragraph/prolog/paragraph.pl')."
echo ""
echo "Load and execute a test suite such as doc_t with:"
echo "?- consult('/opt/paragraph/t/doc_t.plt')."
echo "?- run_tests."
echo ""
docker run -it --rm -v $(realpath .):/opt/paragraph -v $(realpath .)/../pavements:/opt/pavements -v /tmp/paragraph:/tmp/paragraph --env PARAGRAPH_HOME=/opt/paragraph --env PARAGRAPH_TEMP=/tmp/paragraph --env PAVEMENTS_LIBRARY=/opt/pavements/library incodame/swipy
