echo "Welcome to Paragraph. "
echo ""
echo "Configure a working session with:"
echo "?- consult('/opt/paragraph/prolog/paragraph_conf.pl')."
echo "?- paragraph_py_setup."
echo ""
echo "Load some BDSL definitions with:"
echo "?- consult('/opt/paragraph/prolog/bdsl_lib/nodeproj.bdsl.pl')." 
echo "" 
echo "Start a working session with:"
echo "?- pack_install(list_util)."
echo "?- pack_install(regex)."
echo "?- consult('/opt/paragraph/prolog/paragraph.pl')."
echo ""
echo "Load and execute a test suite such as doc_t with:"
echo "?- consult('/opt/paragraph/t/doc_t.plt')."
echo ""
echo "?- run_tests."
#docker run -it --rm -v $(pwd):/opt/paragraph -v /tmp/paragraph:/tmp/paragraph --env PARAGRAPH_HOME=/opt/paragraph --env PARAGRAPH_TEMP=/tmp/paragraph --env IPADDRE=$(ipconfig getifaddr en0) incodame/swipl_images:par_yaml
docker run -it --rm -v $(pwd):/opt/paragraph -v $(pwd)/../pavements:/opt/pavements -v /tmp/paragraph:/tmp/paragraph --env PARAGRAPH_HOME=/opt/paragraph --env PARAGRAPH_TEMP=/tmp/paragraph --env PAVEMENTS_LIBRARY=/opt/pavements/library --env IPADDRE=$(ipconfig getifaddr en0) incodame/swipy
